name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file build/Dockerfile --tag boringtun-builds:$(date +%s) build/

    - uses: actions/checkout@v3
    - name: Build & exctract the BoringTun packages.
      run: cd build; bash ./BUILD.sh


      
